### ISSUE TITLE
型に定義された演算子をいい感じにする

### ISSUE THREAD

**Issue by hafuu** [hafuu/FSharpApiSearch#42]
`op_Equality`を`( = )`など

**Comment by bleis-tift** [comment]
`op_Implicit`や`op_Explicit`をどう表示するか問題

**Comment by hafuu** [comment]
その2つはどうしようもないので、そのまま`op_Implicit`と出すつもり

**Comment by hafuu** [comment]
F# で定義された演算子は`(+)`等で取得できる
C# で定義された演算子は`op_Addition`となる

**Comment by hafuu** [comment]
`Microsoft.FSharp.Compiler.PrettyNaming.CompileOpName`
`Microsoft.FSharp.Compiler.PrettyNaming.DecompileOpName`
を使えば楽にできそう
